inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"

RSpec:
  Language:
    Expectations:
      - expect

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false
