/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ログイン中ユーザー情報取得 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー一覧取得 */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ユーザー詳細取得 */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ユーザー情報更新 */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Todo一覧取得 */
        get: operations["listTodos"];
        put?: never;
        /** Todo作成 */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/todos/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Todo詳細取得 */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /** Todo論理削除 */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        /** Todo更新 */
        patch: operations["updateTodo"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example XVfJTZouHLpN1hnQCSY5i1EeqQ */
            public_id: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example テストユーザー */
            name: string;
            /**
             * @example user
             * @enum {string}
             */
            role: "user" | "admin";
        };
        UserUpdateRequest: {
            user: {
                /** @example 更新後ユーザー */
                name: string;
            };
        };
        Todo: {
            /** @example jZsTMdhGxAzBi76T7LgFE1kEFj */
            public_id: string;
            /** @example 最初のTodo */
            title: string;
            /** @example 動作確認用のTodo */
            description?: string | null;
            /** @example false */
            completed: boolean;
            /**
             * Format: date-time
             * @example 2026-05-28T02:58:04Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @example 2026-05-28T02:58:04Z
             */
            updated_at: string;
        };
        TodoCreateRequest: {
            todo: {
                /** @example 新しいTodo */
                title: string;
                /** @example Todoの説明 */
                description?: string | null;
                /** @example false */
                completed?: boolean;
            };
        };
        TodoUpdateRequest: {
            todo: {
                /** @example 更新後のTodo */
                title?: string;
                /** @example 更新後の説明 */
                description?: string | null;
                /** @example true */
                completed?: boolean;
            };
        };
        ProblemDetails: {
            /** @example https://opentask.example.com/problems/not-found */
            type: string;
            /** @example Not Found */
            title: string;
            /** @example 404 */
            status: number;
            /** @example 指定されたリソースが見つかりません */
            detail: string;
            /** @example not_found */
            reason: string;
            errors?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description 認証エラー */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description 認可エラー */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description リソースが見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description バリデーションエラー */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Userの public_id */
        UserId: string;
        /** @description Todoの public_id */
        TodoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログイン中ユーザー情報 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Userの public_id */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ユーザー詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Userの public_id */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description ユーザー更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoCreateRequest"];
            };
        };
        responses: {
            /** @description Todo作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todoの public_id */
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo詳細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todoの public_id */
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todo削除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Todoの public_id */
                todoId: components["parameters"]["TodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoUpdateRequest"];
            };
        };
        responses: {
            /** @description Todo更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
